#! /bin/bash

set -Eeuo pipefail;

# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2501 -P 8 -t 60 --window=400K --len=128K &
# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2502 -P 8 -t 60 --window=400K --len=128K &
# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2503 -P 8 -t 60 --window=400K --len=128K &
# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2504 -P 8 -t 60 --window=400K --len=128K &
# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2505 -P 8 -t 60 --window=400K --len=128K &
# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2506 -P 8 -t 60 --window=400K --len=128K &
# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2507 -P 8 -t 60 --window=400K --len=128K &
# sudo numactl --physcpubind=0-63 iperf3 -c 192.168.0.2 --port 2508 -P 8 -t 60 --window=400K --len=128K;

iperf_instance_count=8;
cpu_bind_range="0-63";
server_ip="192.168.0.2";
streams_per_instance=8;
instance_run_time_sec=60;
window_size="400K";

for (( i=1; i <= ${iperf_instance_count}; i++ )); do
	sudo numactl --physcpubind=${cpu_bind_range} iperf3	\
		--client ${server_ip}				\
		--port 250${i}					\
		--parallel ${streams_per_instance}		\
		--time ${instance_run_time_sec}			\
		--window ${window_size}				\
		--zerocopy					\
		> ~/iperf3-test/results/client-itr-${i}.log &
done;

