#! /bin/bash

set -Eeuo pipefail

iperf_instance_count=1
cpu_num=31 # NPS4 NUMA node 2 CPU range: 32-47

for ((i = 1; i <= ${iperf_instance_count}; i++)); do
	numactl --physcpubind=32-39 \
		--membind=2 \
		iperf3 \
		--server \
		--one-off \
		--port "250${i}" \
		> "$HOME/iperf3-test/results/server-itr-${i}.log" &
done
